name: Slack Notifications

on:
  workflow_run:
    workflows: ["Deployment"]
    types:
      - completed

jobs:
  slackFailNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: alerts
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON_EMOJI: ':poop:'
        SLACK_MESSAGE: 'There's something up with your push mate'
        SLACK_TITLE: Something's gone wrong
        SLACK_USERNAME: Gary
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}